### ISSUE TITLE
%player_colored_ping% has colors in reverse order

### ISSUE THREAD

**Issue by hensih** [PlaceholderAPI/Player-Expansion#46]
I updated to the latest version and my ping starts at red and goes green if it gets laggy. 

Should be the other way around.

**Comment by Andre601** [comment]
Nothing in the code suggests this behaviour.

On a high ping will the expansion return &c or &4 and on low ping will it be &a.

Double-check that the config of PAPI does have the right values

**Comment by hensih** [comment]
```
  player:
    ping_color:
      medium: '&e'
      high: '&a'
      low: '&c'
```

You are correct.
