### ISSUE TITLE
Allow more ping colors

### ISSUE THREAD

**Issue by RobinRMC** [PlaceholderAPI/Player-Expansion#77]
<h3>Suggestion:</h3>

Add the possibility to add more ping values/colors in the PlaceholderAPI configuration.
<br>

<h3>Example:</h3>

```yaml

  player:
    ping_color:
      extremelyhigh: '&4&l'
      veryhigh: '&4'
      higherthanhigh: '&c'
      high: '&6'
      medium: '&e'
      low: '&b'
      lowerthanlow: '&a'
      verylow: '&d'
      extremelylow: '&5'
    ping_value:
      extremelyhigh: 250
      veryhigh: 200
      higherthanhigh: 150
      high: 100
      medium: 50
      low: 30
      lowerthanlow: 20
      verylow: 10
      extremelylow: 1
```
